<?php
/**
 * This class is autogenerated by Fathom
 *
 * Caution : Do not add any custom methods in this class, the changes you made will be
 * overwritten at the next build time
 */

namespace Fathom\Play\GeneratedMapping;

use Fathom\Mapper\BaseMapper;

class FlagMapper extends BaseMapper
{
    protected $country;

    protected $stock;


    protected $NeoId;

    protected $uuid;

    /**
     * The constructor
     */
    public function __construct()
    {

    }


    /**
     * @var $v
     */
    public function setCountry($v)
    {
        $this->country = $v;
    }

    public function getCountry()
    {
        return $this->country;
    }


    /**
     * @var $v
     */
    public function setStock($v)
    {
        $this->stock = $v;
    }

    public function getStock()
    {
        return $this->stock;
    }


    public function serialize()
    {
        $data = array();
        if(null !== $this->country){
            $data['country'] = $this->getCountry();
        }
        if(null !== $this->stock){
            $data['stock'] = $this->getStock();
        }
        $data['fqdn'] = $this->getNamespace();
        $data['class_name'] = $this->getClassName();
        return $data;
    }

    public function getClassName()
    {
        return 'Flag';
    }

    public function getNamespace()
    {
        return 'Fathom\Play\GeneratedMapping';
    }

    public function getNeoId()
    {
        return $this->neoId;
    }

    public function setNeoId($v)
    {
        $this->neoId = $v;
    }

    public function getUuid()
    {
        return $this->uuid;
    }

    public function setUuid($v)
    {
        $this->uuid = $v;
    }
}