<?php
/**
 * This class is autogenerated by Fathom
 *
 * Caution : Do not add any custom methods in this class, the changes you made will be
 * overwritten at the next build time
 */

namespace Fathom\Play\GeneratedMapping;

use Fathom\Mapper\BaseMapper;

class SimpleNodeMapper extends BaseMapper
{
    protected $username;

    protected $klout;

    protected $timestamp;


    protected $neoId;

    protected $uuid;

    /**
     * The constructor
     */
    public function __construct()
    {

    }


    /**
     * @var $v
     */
    public function setUsername($v)
    {
        $this->username = $v;
    }

    public function getUsername()
    {
        return $this->username;
    }


    /**
     * @var $v
     */
    public function setKlout($v)
    {
        $this->klout = $v;
    }

    public function getKlout()
    {
        return $this->klout;
    }


    /**
     * @var $v
     */
    public function setTimestamp($v)
    {
        $this->timestamp = $v;
    }

    public function getTimestamp()
    {
        return $this->timestamp;
    }


    public function serialize()
    {
        $data = array();
        if(null !== $this->username){
            $data['username'] = $this->getUsername();
        }
        if(null !== $this->klout){
            $data['klout'] = $this->getKlout();
        }
        if(null !== $this->timestamp){
            $data['timestamp'] = $this->getTimestamp();
        }
        $data['fqdn'] = $this->getNamespace();
        $data['class_name'] = $this->getClassName();
        return $data;
    }

    public function getClassName()
    {
        return 'SimpleNode';
    }

    public function getNamespace()
    {
        return 'Fathom\Play\GeneratedMapping';
    }

    public function getNeoId()
    {
        return $this->neoId;
    }

    public function setNeoId($v)
    {
        $this->neoId = $v;
    }

    public function getUuid()
    {
        return $this->uuid;
    }

    public function setUuid($v)
    {
        $this->uuid = $v;
    }
}