<?php
/**
 * This class has been generated by the FathomMapper
 * You can implement here your own logic
 *
*/

namespace Fathom\tests\Schema\Parser\Node;


class SimpleNode
{
    protected $username;

    protected $klout;


    public function __construct()
    {

    }

    public function setUsername($v)
    {
        $this->username = $v;
    }

    public function getUsername()
    {
        return $this->username;
    }

    public function setKlout($v)
    {
        $this->klout = $v;
    }

    public function getKlout()
    {
        return $this->klout;
    }


}