<?php
/**
 * This class has been generated by the FathomMapper
 * You can implement here your own logic
 *
*/

namespace Fathom\tests\Schema\Parser\Node;

use Fathom\tests\Schema\Parser\Node\GeneratedMapping\SimpleNodeMapper;

class SimpleNode extends SimpleNodeMapper
{


}