<?php
/**
 * This class has been generated by the FathomMapper
 * You can implement here your own logic
 *
*/

namespace Fathom\Play;

use Fathom\Play\GeneratedMapping\SimpleNodeMapper;

class SimpleNode extends SimpleNodeMapper
{


}